In [1]:
import pandas as pd
import numpy as np

In [2]:
from google.colab import drive
drive.mount('/sample_data')

Mounted at /sample_data


In [3]:
!ls '/sample_data/MyDrive'

 Academy			    'sidap viki'
'bale bedah'			     SIKRIPSI
'berkas lomba pcta'		     SISKA
 Classroom			     Spkpesiba
'Colab Notebooks'		     test.csv
 data.csv			     train.csv
'data saints'			     Trasnagro
 diabetes-dataset.csv		    'tugas '
'eka depak'			    'UKM Programing'
'flochart sistem pengujian.drawio'  'Untitled Diagram (1).drawio'
 ida				    'Untitled Diagram (2).drawio'
'Khatim Project'		    'Untitled Diagram (3).drawio'
 KKN				    'Untitled Diagram (4).drawio'
'LAPORAN JANAPRIA BENAR.rtf'	    'Untitled Diagram.drawio'
'Laporan PKL'			    'Untitled document.gdoc'
'Lomba PCTA NTB 2019'		    'Untitled drawing.gdraw'
 PKM				    'UTS Kewriausahaan'
'qosriatul amini'		     variabel.rtf
 RSUPraya			     webgis
 seluler.ipynb			     wordpres
 Sertifikat


In [6]:
#importing dataset
Cryotherapy = pd.read_csv("/sample_data/MyDrive/data.csv")

In [7]:
# Menampilkan data
Cryotherapy.head()

sex  age   Time  Number_of_Warts  Type  Area  Result_of_Treatment
0    1   35  12.00                5     1   100                    0
1    1   29   7.00                5     1    96                    1
2    1   50   8.00                1     3   132                    0
3    1   32  11.75                7     3   750                    0
4    1   67   9.25                1     1    42                    0

In [8]:
# menampilkan informasi data
Cryotherapy.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90 entries, 0 to 89
Data columns (total 7 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   sex                  90 non-null     int64  
 1   age                  90 non-null     int64  
 2   Time                 90 non-null     float64
 3   Number_of_Warts      90 non-null     int64  
 4   Type                 90 non-null     int64  
 5   Area                 90 non-null     int64  
 6   Result_of_Treatment  90 non-null     int64  
dtypes: float64(1), int64(6)
memory usage: 5.0 KB


In [9]:
# Mengecek apakah ada deret yang kosong
Cryotherapy.empty

False

In [10]:
# Melihat ukuran dari data
Cryotherapy.size

630

In [12]:
# Variabel independen
x = Cryotherapy.drop(['Result_of_Treatment'], axis = 1)
x.head()

sex  age   Time  Number_of_Warts  Type  Area
0    1   35  12.00                5     1   100
1    1   29   7.00                5     1    96
2    1   50   8.00                1     3   132
3    1   32  11.75                7     3   750
4    1   67   9.25                1     1    42

In [13]:
# Variabel dependen
y = Cryotherapy['Result_of_Treatment']
y.head()

0    0
1    1
2    0
3    0
4    0
Name: Result_of_Treatment, dtype: int64

In [14]:
# Import train_test_split function
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 123)

In [15]:
# Import Gaussian Naive Bayes model
from sklearn.naive_bayes import GaussianNB
# Mengaktifkan/memanggil/membuat fungsi klasifikasi Naive bayes
modelnb = GaussianNB()
# Memasukkan data training pada fungsi klasifikasi naive bayes
nbtrain = modelnb.fit(x_train, y_train)
nbtrain.class_count_

array([33., 39.])

In [16]:
# Menentukan hasil prediksi dari x_test
y_pred = nbtrain.predict(x_test)
y_pred

array([1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1])

In [17]:
# Menentukan probabilitas hasil prediksi
nbtrain.predict_proba(x_test)

array([[2.34336099e-01, 7.65663901e-01],
       [1.65201649e-01, 8.34798351e-01],
       [4.34665582e-01, 5.65334418e-01],
       [9.28100736e-01, 7.18992637e-02],
       [1.00002893e-03, 9.98999971e-01],
       [9.99999912e-01, 8.82148493e-08],
       [6.08424089e-02, 9.39157591e-01],
       [8.23832922e-01, 1.76167078e-01],
       [2.88581316e-03, 9.97114187e-01],
       [9.98354676e-01, 1.64532426e-03],
       [1.00000000e+00, 9.56156555e-57],
       [2.15128221e-01, 7.84871779e-01],
       [1.79795569e-03, 9.98202044e-01],
       [9.99985925e-01, 1.40754598e-05],
       [1.16748529e-02, 9.88325147e-01],
       [9.85529535e-01, 1.44704650e-02],
       [8.71986684e-01, 1.28013316e-01],
       [4.43317684e-02, 9.55668232e-01]])

In [18]:
# import confusion_matrix model
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[7, 2],
       [1, 8]])

In [19]:
# Merapikan hasil confusion matrix
y_actual1 = pd.Series([1, 0,1,0,1,0,1,0,1,0,0,1,1,0,1,1,0,0], name = 'actual')
y_pred1 = pd.Series([1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1], name = 'prediction')
df_confusion = pd.crosstab(y_actual1, y_pred1)
df_confusion

prediction  0  1
actual          
0           7  2
1           1  8

In [20]:
# Menghitung nilai akurasi dari klasifikasi naive bayes 
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.88      0.78      0.82         9
           1       0.80      0.89      0.84         9

    accuracy                           0.83        18
   macro avg       0.84      0.83      0.83        18
weighted avg       0.84      0.83      0.83        18

